name: Android CI

on:
  push:
    branches:
      - 'release_*'
      - 'master'
    tags:
     - "v*"
  pull_request:
    branches: [ "master" ]

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Android Lint
        run: ./gradlew lintDebug

      - name: Lint Report
        uses: yutailang0119/action-android-lint@v3
        with:
          report-path: build/reports/*.xml # Support glob patterns by https://www.npmjs.com/package/@actions/glob
        continue-on-error: false # If annotations contain error of severity, action-android-lint exit 1.

  unit:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code to specific branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Unit tests for Debug build
        run: ./gradlew testDebugUnitTest

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless

#      - name: Qodana Scan
#        uses: JetBrains/qodana-action@main
#        env:
#          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code to specific branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Setup cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Generate app bundle
      run: ./gradlew assembleDebug --stacktrace
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: app/build/outputs/apk/debug/app-debug.apk
  
  release:
    name: Release APK
    needs: build
    runs-on: ubuntu-latest
  
    steps:
    - name: Download APK from build
      uses: actions/download-artifact@v1
      with:
        name: apk
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GHTOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: ${{ github.event.repository.name }} v${{ github.run_number }}
    - name: Upload Release APK
      id: upload_release_asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GHTOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: apk/app-debug.apk
        asset_name: ${{ github.event.repository.name }}.apk
        asset_content_type: application/zip
        
